#!/usr/bin/env bash
# Installs HAProxy version 2.6(LTS) with the following configurations:
# Enables management via the init script.
# Distributes requests using a round-robin algorithm.

#!/usr/bin/env bash
# Install the load balancer


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 57696-web-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 57696-web-02 18.206.208.80:80 check\n\tserver 57696-web-01 54.237.0.244:80  check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
